volumes:
  client_node_modules:
  pg_data:
  # redis_data:
  minio_data:
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - client_node_modules:/app/node_modules
      - ./client:/app
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
      - ./.minio.env
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
    - .minio.env
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data