volumes:
  client_node_modules:
  pg_data:
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - client_node_modules:/app/node_modules
      - ./client:/app
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./postgres/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    env_file:
      - ./minio/.env
    volumes:
      - ./minio/data:/data
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data